config/routes.rb
Rails.application.routes.draw do

  root "users#home"

  resources :users do
    resources :cards
    resources :orders
  end  

  resources :menus
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :user do
    validates :card_number, numericality: { only_integer: true }
    end
    


end

app/models/menu.rb
class Menu < ApplicationRecord
    
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :orders, class_name: "order", foreign_key: "user_id"
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :cards
  has_many :orders
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :user_phonenumber, presence: true, numericality: { only_integer: true }, length: {minimum:10, maximum:10}
  validates :user_address, presence: true
  validates :user_password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def create
    @user = User.find(params[:user_id]) 
    @card = @user.cards.create(card_params)
    redirect_to user_path(@user)
   end

       def destroy
            @user = User.find(params[:user_id])
            @card = @user.cards.find(params[:id])
            @card.destroy
        
            redirect_to user_path(@user), status: :see_other
       end

   private 
       def card_params
           params.require(:card).permit(:card_name, :card_number)
       end
   
    
   end
   

app/controllers/menus_controller.rb
class MenusController < ApplicationController

    def index
    @menus =Menu.all
    end

    def new
        @menu = Menu.new
      end
    
      def create
        @menu = Menu.new(menu_params)
    
        if @menu.save
          redirect_to @menu
        else
          render :new, status: :unprocessable_entity
        end
      end

      private
   def menu_params
     params.require(:menu).permit(:menu_name,:menu_price, :menu_type,:menu_image)
   end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: "Saran", password: "Test@12345", only: :home

  def index
    @users = User.all.order("id ASC") # Returns all users sorted in ascending order by name

  end
  def home
    @user = User.all
  end

    def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  
  private
   def user_params
     params.require(:user).permit(:username,:user_password, :user_address,:user_phonenumber)
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card.html.erb
<%= stylesheet_link_tag "userindex.css" %>
<div class="container">
  <div class="table-wrapper">
    <div class="table-title">
      <div class="row">
        <div class="col-sm-6">
          <h2>Card Details</h2>
        </div>
        
      </div>
    </div>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Card Name</th>
          <th>Card Number</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr> 
          <td><%= card.card_name %></td>
          <td><%= card.card_number %></td>
        

          <td>
            <%= link_to "Delete Card ", [card.user, card] , data: {
              turbo_method: :delete,
              turbo_confirm: :"Are you want to delete the Card Detail?"
            } %> <a class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
          </td>
        </tr>
      </tbody>
    </table>
    
  </div>
</div>

app/views/cards/_form.html.erb
<%= form_with model: [ @user, @user.cards.build ] do |form| %>
  <p>
    <%= form.label :card_name %><br>
    <%= form.text_field :card_name %>
  </p>
  <p>
    <%= form.label :card_number %><br>
    <%= form.password_field :card_number %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodorderingapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"   href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
  
    <%= yield %>
    
  </body>
</html>

app/views/menus/index.html.erb
<%= stylesheet_link_tag "menuindex.css" %>
<header class="header-area">
    <div class="navbar-area">
      <div class="container">
        <nav class="site-navbar">
          <a href="" class="site-logo">SMART ORDER</a>
          <ul>
            <li> <%= link_to "User List", users_path %></li>
            <li><a href="#">Add Admin</a></li>
            <li> <%= link_to "Add  Menu", new_menu_path %> </li>
          </ul>
  
          <button class="nav-toggler">
            <span></span>
          </button>
        </nav>
      </div>
    </div>
<div class="wrapper">
    <h2 class="head-title">Explore Our Foods</h2>
    <p class="head-text">Order Online , Avail Discounts , Get Served On Time At Home</p>
    <div class="cards">
        <% @menus.each do |menu| %>
        <div class="card">
        <img class="card__image" height="300px" width="300px"src="<%= menu.menu_image%>" alt="">
        <div class="card__content">
          <div class="card__header">
            <h4 class="card__title"><%= menu.menu_name %></h4>
            <span class="card__price">Rs.<%= menu.menu_price %></span>
          </div>
          <p class="card__text"><%= menu.menu_type %></p>
        </div>
      </div>
      <%end%>
    </div>
    
</div>

app/views/menus/new.html.erb
<%= stylesheet_link_tag "form.css" %>
<button style="width: 10%;margin-left: 30px;">

  <%= link_to "Home", root_path %> 
</button> 

<%= form_with model: @menu do |form| %>
  <div>
    <%= form.label :menu_name %><br>
    <%= form.text_field :menu_name%>
    <% @menu.errors.full_messages_for(:menu_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :menu_price %><br>
    <%= form.text_field :menu_price %><br>
    <% @menu.errors.full_messages_for(:menu_price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :menu_type %><br>
    <%= form.text_field :menu_type %>
    <% @menu.errors.full_messages_for(:menu_type).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :menu_image %><br>
    <%= form.text_field :menu_image %>
    <% @menu.errors.full_messages_for(:menu_img).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <button type="signup">
    <%= form.submit "Add Menu"%>
  </button>
<% end %>

app/views/users/_form.html.erb
<%= stylesheet_link_tag "form.css" %>
<button style="width: 10%;margin-left: 30px;">

  <%= link_to "Home", root_path %> 
</button> 

<%= form_with model: user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username%>
    <% user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :user_password %><br>
    <%= form.password_field  :user_password %><br>
    <% user.errors.full_messages_for(:user_password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :user_address %><br>
    <%= form.text_field :user_address%>
    <% user.errors.full_messages_for(:user_address).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :user_phonenumber %><br>
    <%= form.text_field :user_phonenumber%>
    <% user.errors.full_messages_for(:user_phonenumber).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <button type="signup">
    <%= form.submit "Add User"%>
  </button>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/home.html.erb
<%= stylesheet_link_tag "home.css" %>
<html>
  <head>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400, 600' rel='stylesheet' type='text/css'>
  <link rel='stylesheet' href='style.css'/>
  </head>
  <body>
    

    <div class="jumbotron">
      <div class="container">  
        <div class="main">
            <h1>Smart Ordering Application</h1>
          <a href="<%=menus_path %>" class="btn-main">User</a>
          
          <a href="<%=users_path %>" class="btn-main">Admin</a>
        </div>
      </div>
    </div>   
  </body>
</html>
  

app/views/users/index.html.erb
<%= stylesheet_link_tag "userindex.css" %>
<header class="header-area">
  <div class="navbar-area">
    <div class="container">
      <nav class="site-navbar">
        <a href="<%root_path %>" class="site-logo">SMART ORDER</a>
        <ul>
          <li> <%= link_to "Menu List", menus_path %>
          </li>
          <li> <%= link_to "Add  User", new_user_path %> </li>
          <li><a href="#">Add Admin</a></li>
        </ul>

        <button class="nav-toggler">
          <span></span>
        </button>
      </nav>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>User Id</th>
          <th>User Name</th>
      
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @users.each do |user| %>
        <tr>
          <td data-th="User Id"><%= user.id %></td>
          <td data-th="UserName"><%= link_to user.username, user %></td>
          <% end %>
        </tr>
      </tr>
      
    </tbody>
  </table>
</header>
 

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= stylesheet_link_tag "show.css" %>

<header class="header-area">
  <div class="navbar-area">
    <div class="container">
      <nav class="site-navbar">
        <a href="#home" class="site-logo">SMART ORDER</a>
        <ul>
          <li> <%= link_to "Home", root_path %> </li>
        </ul>

        <button class="nav-toggler">
          <span></span>
        </button>
      </nav>
    </div>
  </div>


  <div class="container">
    <div class="table-wrapper">
      <div class="table-title">
        <div class="row">
          <div id="user">
            <h3>Manage <b>User</b></h3>
          </div>
          
        </div>
      </div>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>User Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr> 
            <td><%= @user.username %></td>
            <td><%= @user.user_address %></td>
            <td><%= @user.user_phonenumber %></td>
            <td>
              <%= link_to "Edit User Details ", edit_user_path(@user) %><a class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
              <%= link_to "Delete User", user_path(@user), data: {
                turbo_method: :delete,
                turbo_confirm: :"Are you want to delete the User?"}%> <a class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
            </td>
          </tr>
        </tbody>
      </table>
      
    </div>
  </div>

  <h2>Card Details</h2>
  <%= render @user.cards %> 
  <h2>Add a Card:</h2>
  <%= render 'cards/form' %>
</div> 